# Generated by Django 4.0.6 on 2022-08-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220803_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updateed_at',
        ),
    ]
